{% set version = "1.14.1" %}
{% set sha256 = "e0173a675363463c63f52a215e4b3f1bfb28c901d70fe7eea420b5dc4aa591cb" %}

package:
  name: azure-core-cpp
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-core_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # https://github.com/Azure/azure-sdk-for-cpp/issues/4784
    # https://github.com/Azure/azure-sdk-for-cpp/pull/4785
    - 0001-remove-wil-from-exported-config.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("azure-core-cpp", max_pin="x.x.x") }}

# https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/core/azure-core/vcpkg.json
requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libcurl  # [not win]
    - openssl  # [not win]
    - wil  # [win]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  commands:
    # shared libs
    - test -f ${PREFIX}/lib/libazure-core${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_BIN%\azure-core.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\azure-core.lib exit 1  # [win]

    # headers
    - test -f ${PREFIX}/include/azure/core.hpp    # [unix]
    - if not exist %LIBRARY_INC%\azure\core.hpp exit 1  # [win]

    # CMake metadata
    - test -f ${PREFIX}/share/azure-core-cpp/azure-core-cppTargets.cmake                     # [unix]
    - if not exist %LIBRARY_PREFIX%\share\azure-core-cpp\azure-core-cppTargets.cmake exit 1  # [win]

    # CMake find_package() and target_link_libraries()
    - cmake $CMAKE_ARGS -G Ninja -S $RECIPE_DIR/test-linking-src -B test-linking-bld    # [unix]
    - cmake %CMAKE_ARGS% -G Ninja -S %RECIPE_DIR%\test-linking-src -B test-linking-bld  # [win]
    - cmake --build test-linking-bld
    - cmake --build test-linking-bld --target test

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure SDK Core Library for C++
  description: >-
    Azure::Core (`azure-core`) provides shared primitives, abstractions, and helpers for modern Azure SDK client libraries written in the C++
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/core/azure-core/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/core/azure-core/

extra:
  recipe-maintainers:
    - teo-tsirpanis
    - jdblischak
    - jjerphan
    - Shelnutt2
